// Copyright Buckley Builds LLC. All Rights Reserved.

#include "GameIQBlueprintCommandlet.h"

#include "AssetRegistry/ARFilter.h"
#include "AssetRegistry/AssetData.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "AssetRegistry/IAssetRegistry.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "Engine/Blueprint.h"
#include "Engine/SCS_Node.h"
#include "Engine/SimpleConstructionScript.h"
#include "GameIQHash.h"
#include "GameIQJson.h"
#include "HAL/FileManager.h"
#include "HAL/PlatformTime.h"
#include "K2Node_CallFunction.h"
#include "K2Node_Event.h"
#include "K2Node_EventNodeInterface.h"
#include "K2Node_FunctionEntry.h"
#include "K2Node_MathExpression.h"
#include "Misc/Parse.h"
#include "Misc/Paths.h"
#include "Modules/ModuleManager.h"
#include "UObject/PropertyPortFlags.h"
#include "UObject/UnrealType.h"
#include "UObject/UObjectGlobals.h"

DEFINE_LOG_CATEGORY_STATIC(LogGameIQBlueprints, Log, All);

namespace
{
	const TCHAR* BlueprintProducer = TEXT("gameiq-ue-bp@0.1.0");
	constexpr int32 MaxNodesPerGraph = 400; // guard against pathological graphs

	// See GameIQAssetCommandlet.cpp's AssetGCFlushInterval: a full GC pass costs O(entire live
	// UObject graph), so flushing every N loaded Blueprints amortizes that cost while still
	// bounding peak memory across a full /Game scan.
	// (Named per-commandlet: unity builds merge these anonymous namespaces into one TU.)
	constexpr int32 BlueprintGCFlushInterval = 300;

	FString NodeTitle(const UEdGraphNode* Node)
	{
		// UK2Node_MathExpression::GetNodeTitle() can crash headlessly (no interactive editor) when
		// the expression references a variable by GUID: it resolves the owning Blueprint via
		// GetBlueprint() (FBlueprintEditorUtils::FindBlueprintForNode), which can return a Blueprint
		// whose ParentClass isn't resolved outside a fully-loaded editor context, and
		// FindMemberVariableNameByGuid() then null-derefs walking ParentClass->ClassGeneratedBy.
		// Read the node's own raw expression text directly instead — it's plain reflected data, safe
		// to read unconditionally, and arguably more useful for a search index than the interactive
		// "friendly" title anyway (e.g. "Health * 2 + Offset" instead of the resolved display form).
		if (const UK2Node_MathExpression* MathExpr = Cast<UK2Node_MathExpression>(Node))
		{
			return MathExpr->Expression.IsEmpty() ? TEXT("Math Expression") : MathExpr->Expression;
		}
		return GameIQ::OneLine(Node->GetNodeTitle(ENodeTitleType::ListView).ToString());
	}

	bool IsExecPin(const UEdGraphPin* Pin)
	{
		return Pin && Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Exec;
	}

	/** Human-readable type for a Blueprint variable/pin, e.g. `float`, `HealthComponent`, `Array<Actor>`. */
	FString PinTypeToString(const FEdGraphPinType& T)
	{
		FString Base = T.PinCategory.ToString();
		if (const UObject* Sub = T.PinSubCategoryObject.Get()) { Base = Sub->GetName(); }
		switch (T.ContainerType)
		{
			case EPinContainerType::Array: return FString::Printf(TEXT("Array<%s>"), *Base);
			case EPinContainerType::Set:   return FString::Printf(TEXT("Set<%s>"), *Base);
			case EPinContainerType::Map:   return FString::Printf(TEXT("Map<%s>"), *Base);
			default:                       return Base;
		}
	}

	/** If a pin type references a UClass (object/class/interface pins), return its reflection name. */
	const UClass* PinTypeClass(const FEdGraphPinType& T)
	{
		return Cast<UClass>(T.PinSubCategoryObject.Get());
	}

	/** A node with no exec pins is a pure/data-only node — safe to inline into a caller's args. */
	bool IsPureNode(const UEdGraphNode* Node)
	{
		for (const UEdGraphPin* Pin : Node->Pins)
		{
			if (IsExecPin(Pin)) { return false; }
		}
		return true;
	}

	FString NodeSignatureRec(const UEdGraphNode* Node, int32 Depth);

	/** A readable value for an input data pin: the upstream node (pure ones inlined) or a literal default. */
	FString InputPinValue(const UEdGraphPin* Pin, int32 Depth)
	{
		if (Pin->LinkedTo.Num() > 0)
		{
			const UEdGraphPin* Src = Pin->LinkedTo[0];
			const UEdGraphNode* SrcNode = Src ? Src->GetOwningNode() : nullptr;
			if (SrcNode)
			{
				// Inline pure data chains so `Set X(Value=A * B)` reads through, not just `Multiply`.
				if (Depth < 3 && IsPureNode(SrcNode)) { return NodeSignatureRec(SrcNode, Depth + 1); }
				return NodeTitle(SrcNode);
			}
		}
		if (Pin->DefaultObject) { return Pin->DefaultObject->GetName(); }
		if (!Pin->DefaultValue.IsEmpty()) { return Pin->DefaultValue; }
		if (!Pin->AutogeneratedDefaultValue.IsEmpty()) { return Pin->AutogeneratedDefaultValue; }
		return FString();
	}

	/** Node title plus its meaningful data inputs, e.g. `Set Actor Location(NewLocation=Get Center)`. */
	FString NodeSignatureRec(const UEdGraphNode* Node, int32 Depth)
	{
		TArray<FString> Args;
		for (const UEdGraphPin* Pin : Node->Pins)
		{
			if (!Pin || Pin->Direction != EGPD_Input || IsExecPin(Pin)) { continue; }
			if (Pin->bHidden) { continue; }
			const FString Value = InputPinValue(Pin, Depth);
			if (!Value.IsEmpty())
			{
				Args.Add(FString::Printf(TEXT("%s=%s"), *Pin->PinName.ToString(), *GameIQ::OneLine(Value)));
			}
		}
		const FString Title = NodeTitle(Node);
		return Args.Num() > 0 ? FString::Printf(TEXT("%s(%s)"), *Title, *FString::Join(Args, TEXT(", "))) : Title;
	}

	FString NodeSignature(const UEdGraphNode* Node) { return NodeSignatureRec(Node, 0); }

	int32 ExecOutPinCount(const UEdGraphNode* Node)
	{
		int32 N = 0;
		for (const UEdGraphPin* Pin : Node->Pins)
		{
			if (Pin && Pin->Direction == EGPD_Output && IsExecPin(Pin)) { ++N; }
		}
		return N;
	}

	/** Follow exec wires from a node, emitting indented pseudocode. Branch/Sequence pins are labelled. */
	void WalkExec(const UEdGraphNode* Node, int32 Indent, TSet<const UEdGraphNode*>& Visited, FString& Out)
	{
		const FString Pad = FString::ChrN(Indent * 2, TEXT(' '));
		if (Indent > 40 || Out.Len() > 16000) { return; }
		if (Visited.Contains(Node))
		{
			Out += Pad + TEXT("→ ") + NodeTitle(Node) + TEXT(" (see above)\n");
			return;
		}
		Visited.Add(Node);
		Out += Pad + NodeSignature(Node) + TEXT("\n");

		const bool bLabel = ExecOutPinCount(Node) > 1;
		for (const UEdGraphPin* Pin : Node->Pins)
		{
			if (!Pin || Pin->Direction != EGPD_Output || !IsExecPin(Pin)) { continue; }
			for (const UEdGraphPin* Linked : Pin->LinkedTo)
			{
				const UEdGraphNode* Next = Linked ? Linked->GetOwningNode() : nullptr;
				if (!Next) { continue; }
				if (bLabel) { Out += Pad + FString::Printf(TEXT("  [%s]\n"), *Pin->PinName.ToString()); }
				WalkExec(Next, Indent + (bLabel ? 2 : 1), Visited, Out);
			}
		}
	}

	/** Entry-ordered pseudocode: start at events/function entries and trace exec flow. */
	FString RenderGraph(const UEdGraph* Graph)
	{
		TArray<const UEdGraphNode*> Entries;
		for (const UEdGraphNode* Node : Graph->Nodes)
		{
			// Event roots: classic events + function entries, plus anything implementing the event-node
			// interface — Enhanced Input action events (UK2Node_EnhancedInputAction) and legacy
			// InputAction/InputKey/InputTouch nodes. Without this, a character's IA_Move/IA_Jump → handler
			// bindings render as nothing (they're not UK2Node_Event), so "how does input work" comes up empty.
			if (Cast<const UK2Node_Event>(Node) || Cast<const UK2Node_FunctionEntry>(Node)
				|| (Node && Node->GetClass()->ImplementsInterface(UK2Node_EventNodeInterface::StaticClass())))
			{
				Entries.Add(Node);
			}
		}
		if (Entries.Num() == 0)
		{
			// Fallback: exec nodes with an outgoing exec wire but no incoming one are roots.
			for (const UEdGraphNode* Node : Graph->Nodes)
			{
				if (!Node) { continue; }
				bool bOut = false, bIn = false;
				for (const UEdGraphPin* Pin : Node->Pins)
				{
					if (!IsExecPin(Pin) || Pin->LinkedTo.Num() == 0) { continue; }
					if (Pin->Direction == EGPD_Output) { bOut = true; }
					else if (Pin->Direction == EGPD_Input) { bIn = true; }
				}
				if (bOut && !bIn) { Entries.Add(Node); }
			}
		}

		FString Out;
		TSet<const UEdGraphNode*> Visited;
		for (const UEdGraphNode* Entry : Entries)
		{
			WalkExec(Entry, 0, Visited, Out);
			Out += TEXT("\n");
		}

		// Pure/data-only graphs (no exec flow): fall back to a flat node listing so nothing is invisible.
		if (Out.TrimStartAndEnd().IsEmpty())
		{
			int32 Count = 0;
			for (const UEdGraphNode* Node : Graph->Nodes)
			{
				if (!Node) { continue; }
				if (++Count > MaxNodesPerGraph) { break; }
				Out += FString::Printf(TEXT("- %s\n"), *NodeSignature(Node));
			}
		}
		return Out;
	}
}

void GameIQBlueprint::ExtractBlueprint(
	UBlueprint* BP,
	TArray<TSharedPtr<FJsonValue>>& Entities,
	TArray<TSharedPtr<FJsonValue>>& Edges,
	TArray<TSharedPtr<FJsonValue>>& Chunks)
{
	if (!BP) { return; }
	const FString Package = BP->GetOutermost()->GetName();
	const FString AssetName = BP->GetName();
	const FString BpId = FString::Printf(TEXT("asset:%s"), *Package);

	// Gather graphs: event graphs (ubergraph pages) + function graphs.
	TArray<UEdGraph*> Graphs;
	Graphs.Append(BP->UbergraphPages);
	Graphs.Append(BP->FunctionGraphs);

	for (const UEdGraph* Graph : Graphs)
	{
		if (!Graph) { continue; }
		const FString GraphName = Graph->GetName();
		const FString Pseudo = RenderGraph(Graph);
		if (Pseudo.IsEmpty()) { continue; }

		const FString FnId = FString::Printf(TEXT("%s::%s"), *BpId, *GraphName);
		Entities.Add(MakeShared<FJsonValueObject>(GameIQ::MakeEntity(
			FnId, TEXT("bp-function"), GraphName, Package, TEXT("asset"), BpId,
			FString::Printf(TEXT("%s graph of %s"), *GraphName, *AssetName), nullptr)));

		Chunks.Add(MakeShared<FJsonValueObject>(GameIQ::MakeChunk(
			FString::Printf(TEXT("%s#pseudo"), *FnId), FnId, TEXT("bp-pseudocode"),
			FString::Printf(TEXT("%s :: %s\n%s"), *AssetName, *GraphName, *Pseudo))));

		for (const UEdGraphNode* Node : Graph->Nodes)
		{
			const UK2Node_CallFunction* Call = Cast<UK2Node_CallFunction>(Node);
			if (!Call) { continue; }
			const UFunction* Fn = Call->GetTargetFunction();
			if (!Fn) { continue; }
			const UClass* Owner = Fn->GetOwnerClass();
			if (!Owner) { continue; }
			Edges.Add(MakeShared<FJsonValueObject>(GameIQ::MakeEdge(
				BpId, FString::Printf(TEXT("cpp:%s"), *Owner->GetName()), TEXT("calls"), Fn->GetName())));
		}
	}

	// --- Blueprint structure beyond graphs: variables, components, interfaces ---
	const FString ParentName = BP->ParentClass ? BP->ParentClass->GetName() : FString();
	// The class default object holds each variable's actual default value (reflects value edits).
	const UObject* CDO = BP->GeneratedClass ? BP->GeneratedClass->GetDefaultObject() : nullptr;
	TArray<FString> VarLines, CompLines, IfaceLines;

	for (const FBPVariableDescription& Var : BP->NewVariables)
	{
		const FString VarName = Var.VarName.ToString();
		const FString TypeStr = PinTypeToString(Var.VarType);

		// Prefer the live default from the CDO; fall back to the authored default string.
		FString DefaultVal = Var.DefaultValue;
		if (CDO)
		{
			if (const FProperty* Prop = CDO->GetClass()->FindPropertyByName(Var.VarName))
			{
				FString V;
				Prop->ExportTextItem_Direct(V, Prop->ContainerPtrToValuePtr<void>(CDO), nullptr,
					const_cast<UObject*>(CDO), PPF_None);
				if (!V.IsEmpty()) { DefaultVal = V; }
			}
		}

		TSharedRef<FJsonObject> D = MakeShared<FJsonObject>();
		D->SetStringField(TEXT("type"), TypeStr);
		D->SetStringField(TEXT("category"), Var.Category.ToString());
		if (!DefaultVal.IsEmpty()) { D->SetStringField(TEXT("default"), DefaultVal); }
		const FString VarSummary = DefaultVal.IsEmpty()
			? FString::Printf(TEXT("%s %s"), *TypeStr, *VarName)
			: FString::Printf(TEXT("%s %s = %s"), *TypeStr, *VarName, *DefaultVal);
		Entities.Add(MakeShared<FJsonValueObject>(GameIQ::MakeEntity(
			FString::Printf(TEXT("%s::var::%s"), *BpId, *VarName), TEXT("bp-variable"), VarName,
			Package, TEXT("asset"), BpId, VarSummary, D)));
		VarLines.Add(DefaultVal.IsEmpty()
			? FString::Printf(TEXT("%s: %s"), *VarName, *TypeStr)
			: FString::Printf(TEXT("%s: %s = %s"), *VarName, *TypeStr, *DefaultVal));
		if (const UClass* C = PinTypeClass(Var.VarType))
		{
			Edges.Add(MakeShared<FJsonValueObject>(GameIQ::MakeEdge(
				BpId, FString::Printf(TEXT("cpp:%s"), *C->GetName()), TEXT("references"), VarName)));
		}
	}

	if (BP->SimpleConstructionScript)
	{
		for (const USCS_Node* Node : BP->SimpleConstructionScript->GetAllNodes())
		{
			if (!Node) { continue; }
			const FString CompName = Node->GetVariableName().ToString();
			const UClass* CompClass = Node->ComponentClass;
			const FString ClassName = CompClass ? CompClass->GetName() : TEXT("Component");
			TSharedRef<FJsonObject> D = MakeShared<FJsonObject>();
			D->SetStringField(TEXT("componentClass"), ClassName);
			if (!Node->ParentComponentOrVariableName.IsNone())
			{
				D->SetStringField(TEXT("attachParent"), Node->ParentComponentOrVariableName.ToString());
			}
			Entities.Add(MakeShared<FJsonValueObject>(GameIQ::MakeEntity(
				FString::Printf(TEXT("%s::comp::%s"), *BpId, *CompName), TEXT("bp-component"), CompName,
				Package, TEXT("asset"), BpId, FString::Printf(TEXT("%s %s"), *ClassName, *CompName), D)));
			CompLines.Add(FString::Printf(TEXT("%s: %s"), *CompName, *ClassName));
			if (CompClass)
			{
				Edges.Add(MakeShared<FJsonValueObject>(GameIQ::MakeEdge(
					BpId, FString::Printf(TEXT("cpp:%s"), *ClassName), TEXT("references"), CompName)));
			}
		}
	}

	for (const FBPInterfaceDescription& Iface : BP->ImplementedInterfaces)
	{
		const UClass* IfClass = Iface.Interface.Get();
		if (!IfClass) { continue; }
		IfaceLines.Add(IfClass->GetName());
		Edges.Add(MakeShared<FJsonValueObject>(GameIQ::MakeEdge(
			BpId, FString::Printf(TEXT("cpp:%s"), *IfClass->GetName()), TEXT("implements"), FString())));
	}

	FString S = AssetName;
	if (!ParentName.IsEmpty()) { S += FString::Printf(TEXT(" (parent: %s)"), *ParentName); }
	S += TEXT("\n");
	if (VarLines.Num() > 0)   { S += TEXT("Variables: ")  + FString::Join(VarLines, TEXT(", "))  + TEXT("\n"); }
	if (CompLines.Num() > 0)  { S += TEXT("Components: ") + FString::Join(CompLines, TEXT(", ")) + TEXT("\n"); }
	if (IfaceLines.Num() > 0) { S += TEXT("Implements: ") + FString::Join(IfaceLines, TEXT(", ")) + TEXT("\n"); }
	Chunks.Add(MakeShared<FJsonValueObject>(GameIQ::MakeChunk(
		FString::Printf(TEXT("%s#structure"), *BpId), BpId, TEXT("recipe-summary"), S)));
}

UGameIQBlueprintsCommandlet::UGameIQBlueprintsCommandlet()
{
	IsClient = false;
	IsServer = false;
	IsEditor = true;
	LogToConsole = true;
	ShowErrorCount = false; // benign engine load warnings shouldn't inflate the error count
}

int32 UGameIQBlueprintsCommandlet::Main(const FString& Params)
{
	FString OutDir;
	if (!FParse::Value(*Params, TEXT("out="), OutDir))
	{
		OutDir = FPaths::Combine(FPaths::ProjectDir(), TEXT(".gameiq"), TEXT("extract"));
	}
	IFileManager::Get().MakeDirectory(*OutDir, /*Tree=*/true);

	// Incremental rebuild (-full forces a from-scratch pass, ignoring/overwriting the cache).
	const bool bForceFull = FParse::Param(*Params, TEXT("full"));
	const FString HashCachePath = FPaths::Combine(OutDir, TEXT("blueprint-hashes.json"));
	TMap<FString, GameIQHash::FCachedAssetRow> PrevCache =
		bForceFull ? TMap<FString, GameIQHash::FCachedAssetRow>() : GameIQHash::LoadAssetHashCache(HashCachePath);
	TMap<FString, GameIQHash::FCachedAssetRow> NewCache;
	NewCache.Reserve(PrevCache.Num());

	FAssetRegistryModule& ARM =
		FModuleManager::LoadModuleChecked<FAssetRegistryModule>(TEXT("AssetRegistry"));
	IAssetRegistry& AR = ARM.Get();
	AR.SearchAllAssets(/*bSynchronous=*/true);

	FARFilter Filter;
	Filter.ClassPaths.Add(UBlueprint::StaticClass()->GetClassPathName());
	Filter.bRecursiveClasses = true;
	Filter.PackagePaths.Add(FName(TEXT("/Game")));
	Filter.bRecursivePaths = true;

	TArray<FAssetData> BlueprintAssets;
	AR.GetAssets(Filter, BlueprintAssets);

	TArray<TSharedPtr<FJsonValue>> Entities;
	TArray<TSharedPtr<FJsonValue>> Edges;
	TArray<TSharedPtr<FJsonValue>> Chunks;

	const int32 TotalBlueprints = BlueprintAssets.Num();
	int32 Rendered = 0;
	int32 Skipped = 0;
	int32 Index = 0;
	int32 LoadedSinceLastGC = 0;
	double LastProgressLogTime = FPlatformTime::Seconds();
	for (const FAssetData& Data : BlueprintAssets)
	{
		++Index;
		const double Now = FPlatformTime::Seconds();
		if (Now - LastProgressLogTime >= 2.0)
		{
			UE_LOG(LogGameIQBlueprints, Display, TEXT("Game IQ blueprints: %d/%d scanned (%d rendered, %d skipped-unchanged so far)..."),
				Index, TotalBlueprints, Rendered - Skipped, Skipped);
			LastProgressLogTime = Now;
		}

		const FString Id = GameIQHash::AssetIdOfPackage(Data.PackageName);
		const FString Sig = GameIQHash::ComputeChangeSignature(AR, Data);

		// Incremental rebuild: an unchanged Blueprint's previously-extracted rows (graphs, vars,
		// components) are carried forward verbatim — see GameIQAssetCommandlet.cpp for the same
		// pattern. An empty Sig ("unknown") is never cached/matched, so it's always reprocessed.
		if (!Sig.IsEmpty())
		{
			if (const GameIQHash::FCachedAssetRow* Cached = PrevCache.Find(Id))
			{
				if (Cached->Signature == Sig)
				{
					Entities.Append(Cached->Entities);
					Edges.Append(Cached->Edges);
					Chunks.Append(Cached->Chunks);
					NewCache.Add(Id, *Cached);
					++Rendered;
					++Skipped;
					continue;
				}
			}
		}

		const int32 EntitiesBefore = Entities.Num();
		const int32 EdgesBefore = Edges.Num();
		const int32 ChunksBefore = Chunks.Num();

		UBlueprint* BP = Cast<UBlueprint>(Data.GetAsset());
		if (!BP) { continue; }
		GameIQBlueprint::ExtractBlueprint(BP, Entities, Edges, Chunks);
		++Rendered;

		// Bound peak memory across a full /Game scan: nothing here holds a reference to BP (or the
		// dependencies it pulled in) past this point, so a periodic flush lets the GC actually
		// reclaim them — a commandlet's Main() never yields back to the engine tick loop that
		// would otherwise trigger this automatically.
		if (++LoadedSinceLastGC >= BlueprintGCFlushInterval)
		{
			CollectGarbage(RF_NoFlags, /*bPerformFullPurge=*/true);
			LoadedSinceLastGC = 0;
		}

		if (!Sig.IsEmpty())
		{
			GameIQHash::FCachedAssetRow Row;
			Row.Signature = Sig;
			if (const int32 N = Entities.Num() - EntitiesBefore) { Row.Entities.Append(Entities.GetData() + EntitiesBefore, N); }
			if (const int32 N = Edges.Num() - EdgesBefore) { Row.Edges.Append(Edges.GetData() + EdgesBefore, N); }
			if (const int32 N = Chunks.Num() - ChunksBefore) { Row.Chunks.Append(Chunks.GetData() + ChunksBefore, N); }
			NewCache.Add(Id, MoveTemp(Row));
		}
	}

	GameIQHash::SaveAssetHashCache(HashCachePath, NewCache);

	if (!GameIQ::WriteOutput(OutDir, TEXT("blueprints.json"), BlueprintProducer, Entities, Edges, Chunks))
	{
		UE_LOG(LogGameIQBlueprints, Error, TEXT("Failed to write blueprints.json to %s"), *OutDir);
		return 1;
	}

	UE_LOG(LogGameIQBlueprints, Display,
		TEXT("Game IQ: rendered %d Blueprints (%d skipped, unchanged) — %d entities (graphs/vars/components), %d edges, %d chunks to %s"),
		Rendered, Skipped, Entities.Num(), Edges.Num(), Chunks.Num(), *FPaths::Combine(OutDir, TEXT("blueprints.json")));
	return 0;
}
